//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektBD2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HCO()
        {
            this.HCP = new HashSet<HCP>();
        }
    
        public int HCOID { get; set; }
        public string Name { get; set; }
        public string Range { get; set; }
        public short Level { get; set; }
        public string SpecialType { get; set; }
        public string Beds { get; set; }
        public string Employees { get; set; }
        public int PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public int AddressID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HCP> HCP { get; set; }
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
    }
}
