//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektBD2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HCP()
        {
            this.KOL = false;
            this.Meeting = new HashSet<Meeting>();
        }
    
        public int HCPID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string AcademicTitle { get; set; }
        public System.DateTime Birthdate { get; set; }
        public int PhoneNumber { get; set; }
        public string Email { get; set; }
        public bool KOL { get; set; }
        public string Specialty { get; set; }
        public int AddressID { get; set; }
        public int HCOID { get; set; }
    
        public virtual HCO HCO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting> Meeting { get; set; }
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
    }
}
