//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektBD2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int MeetingID { get; set; }
        public int HCPID { get; set; }
        public System.DateTime Date { get; set; }
        public string Topic { get; set; }
        public int AddressID { get; set; }
        public int ProductID { get; set; }
        public int UserID { get; set; }
    
        public virtual Address Address1 { get; set; }
        public virtual HCP HCP { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
